package com.hd123.baas.sop.config;

import com.qianfan123.baas.config.api.annotation.BcGroup;
import com.qianfan123.baas.config.api.annotation.BcKey;
import com.qianfan123.baas.config.api.field.ConfigEditor;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@BcGroup(name = "菜单")
public class MenuConfig {

  private static final String PREFIX = "menu.";

  @BcKey(name = "默认的菜单集合", editor = ConfigEditor.JSON)
  private String defaultJson = "[" +
      "{\"title\":\"首页\",\"icon\":\"shouye\",\"code\":\"shouye\",\"children\":[{\"title\":\"首页\",\"path\":\"/home\",\"code\":\"Home\",\"icon\":\"renwu1\"}]}" +
      ",{\"title\":\"店务\",\"icon\":\"dianwu\",\"code\":\"shopOperation\",\"children\":[{\"title\":\"爆品订货\",\"path\":\"/shopOperation/orderExplosive\",\"code\":\"OrderExplosive\",\"icon\":\"dianwu1\"},{\"title\":\"质量反馈\",\"path\":\"/shopOperation/qualityFeedback\",\"code\":\"QualityFeedback\",\"icon\":\"dianwu1\"},{\"title\":\"调拨申请\",\"path\":\"/shopOperation/invFXApplyList\",\"code\":\"InvFXApplyList\",\"icon\":\"dianwu2\"},{\"title\":\"门店管理\",\"path\":\"/shopOperation/shopList\",\"code\":\"ShopList\",\"icon\":\"dianwu3\"},{\"title\":\"补贴计划管理\",\"path\":\"/shopOperation/subsidyPlanList\",\"code\":\"SubsidyPlanList\",\"icon\":\"dianwu4\"}]}" +
      ",{\"title\":\"任务\",\"icon\":\"renwu\",\"code\":\"task\",\"children\":[{\"title\":\"任务中心\",\"path\":\"/task/centreList\",\"code\":\"CentreList\",\"icon\":\"renwu1\"},{\"title\":\"单次任务\",\"path\":\"/task/singleList\",\"code\":\"SingleList\",\"icon\":\"renwu2\"},{\"title\":\"周期性任务\",\"path\":\"/task/cycleList\",\"code\":\"CycleList\",\"icon\":\"renwu3\"},{\"title\":\"任务日程\",\"path\":\"/task/schedule\",\"code\":\"Schedule\",\"icon\":\"renwu4\"},{\"title\":\"督导评价\",\"path\":\"/task/evaluateList\",\"code\":\"EvaluateList\",\"icon\":\"renwu5\"},{\"title\":\"总部审核\",\"path\":\"/task/auditList\",\"code\":\"AuditList\",\"icon\":\"renwu6\"},{\"title\":\"任务设置\",\"path\":\"/task/setting\",\"code\":\"Setting\",\"icon\":\"renwu7\"}]}" +
      ",{\"title\":\"巡检\",\"icon\":\"xunjian\",\"code\":\"inspection\",\"children\":[{\"title\":\"巡检中心\",\"path\":\"/inspection/centreList\",\"code\":\"InsCentreList\",\"icon\":\"xunjian1\"},{\"title\":\"单次巡检\",\"path\":\"/inspection/singleList\",\"code\":\"InsSingleList\",\"icon\":\"xunjian2\"},{\"title\":\"周期性巡检\",\"path\":\"/inspection/cycleList\",\"code\":\"InsCycleList\",\"icon\":\"xunjian3\"},{\"title\":\"督导日程\",\"path\":\"/inspection/schedule\",\"code\":\"InsSchedule\",\"icon\":\"xunjian4\"},{\"title\":\"巡检审核\",\"path\":\"/inspection/auditList\",\"code\":\"InsAuditList\",\"icon\":\"xunjian5\"},{\"title\":\"巡检设置\",\"path\":\"/inspection/setting\",\"code\":\"InsSetting\",\"icon\":\"xunjian6\"}]}" +
      ",{\"title\":\"商品\",\"icon\":\"shangpin\",\"code\":\"shop\",\"children\":[{\"title\":\"门店商品\",\"path\":\"/shop/skuDirList\",\"code\":\"SkuDirList\",\"icon\":\"shangpin1\"},{\"title\":\"商品标签\",\"path\":\"/shop/skuTagList\",\"code\":\"SkuTagList\",\"icon\":\"shangpin2\"},{\"title\":\"库存查询\",\"path\":\"/shop/skuInvQuery\",\"code\":\"SkuInvQuery\",\"icon\":\"shangpin1\"},{\"title\":\"上下架管理\",\"path\":\"/shop/skuPublishPlan\",\"code\":\"SkuPublishPlan\",\"icon\":\"shangpin2\"}]}" +
      ",{\"title\":\"营销\",\"icon\":\"yingxiao\",\"code\":\"marketing\",\"children\":[{\"title\":\"模板管理\",\"path\":\"/marketing/promTemplate\",\"code\":\"PromTemplateList\",\"icon\":\"yingxiao1\"},{\"title\":\"营销玩法\",\"path\":\"/marketing/promRule\",\"code\":\"PromRule\",\"icon\":\"yingxiao2\"},{\"title\":\"活动管理\",\"path\":\"/marketing/promActivity\",\"code\":\"PromActivityList\",\"icon\":\"yingxiao3\"},{\"title\":\"爆品活动\",\"path\":\"/marketing/explosiveActivity\",\"code\":\"ExplosiveActivityList\",\"icon\":\"yingxiao4\"}]},{\"title\":\"公告\",\"icon\":\"gonggao\",\"code\":\"announcement\",\"children\":[{\"title\":\"公告管理\",\"path\":\"/announcement\",\"code\":\"AnnouncementList\",\"icon\":\"gonggao1\"}]}" +
      ",{\"title\":\"价格\",\"icon\":\"jiage\",\"code\":\"priceMgr\",\"children\":[{\"title\":\"价格基础设置\",\"path\":\"/price/settings\",\"code\":\"PriceSettings\",\"icon\":\"jiage1\"},{\"title\":\"价格试算\",\"path\":\"/price/adjustment\",\"code\":\"PriceAdjustmentList\",\"icon\":\"jiage2\"},{\"title\":\"门店价格策略\",\"path\":\"/price/gradeAdjustment\",\"code\":\"GradeAdjustment\",\"icon\":\"jiage3\"},{\"title\":\"到店价促销\",\"path\":\"/price/storePrmPrice\",\"code\":\"StorePrmPriceList\",\"icon\":\"jiage4\"},{\"title\":\"到店价模型促销\",\"path\":\"/mkhpms/basePriceProm\",\"code\":\"BasePricePromReqList\",\"icon\":\"jiage5\"},{\"title\":\"售价查询\",\"path\":\"/price/query\",\"code\":\"PriceQuery\",\"icon\":\"jiage6\"},{\"title\":\"临时改价\",\"path\":\"/price/tempAdjustment\",\"code\":\"TempAdjustment\",\"icon\":\"jiage7\"},{\"title\":\"导入到店价\",\"path\":\"/price/tempShopAdjustment\",\"code\":\"TempShopAdjustment\",\"icon\":\"jiage8\"}]}" +
      ",{\"title\":\"设备\",\"icon\":\"shebei\",\"code\":\"equipment\",\"children\":[{\"title\":\"秤模板管理\",\"path\":\"/equipment/electronicTpl\",\"code\":\"ElectronicScaleTplList\",\"icon\":\"shebei1\"},{\"title\":\"电子秤\",\"path\":\"/equipment/electronicScale\",\"code\":\"ElectronicScaleList\",\"icon\":\"shebei2\"},{\"title\":\"收银机\",\"path\":\"/equipment/pos\",\"code\":\"PosList\",\"icon\":\"shebei3\"},{\"title\":\"价格屏\",\"path\":\"/equipment/priceScreen\",\"code\":\"PriceScreen\",\"icon\":\"shebei4\"}]}" +
      ",{\"title\":\"内容\",\"icon\":\"neirong\",\"code\":\"cms\",\"children\":[{\"title\":\"副屏广告\",\"path\":\"/cms/adsScheme\",\"code\":\"AdsSchemeList\",\"icon\":\"neirong1\"},{\"title\":\"图文投放\",\"path\":\"/cms/advertorial\",\"code\":\"AdvertorialList\",\"icon\":\"neirong2\"},{\"title\":\"常用问题管理\",\"path\":\"/cms/proManagement\",\"code\":\"ProManagementList\",\"icon\":\"neirong3\"}]}" +
      ",{\"title\":\"鲜食\",\"icon\":\"xianshi\",\"code\":\"fresh\",\"children\":[{\"title\":\"解冻时间\",\"path\":\"/fresh/thawingTime\",\"code\":\"ThawingTime\",\"icon\":\"xianshi1\"},{\"title\":\"餐段管理\",\"path\":\"/fresh/mealManagement\",\"code\":\"MealManagementList\",\"icon\":\"xianshi2\"},{\"title\":\"商品分类\",\"path\":\"/fresh/skuClassify\",\"code\":\"SkuClassifyList\",\"icon\":\"xianshi3\"},{\"title\":\"商品管理\",\"path\":\"/fresh/skuManagement\",\"code\":\"SkuManagementList\",\"icon\":\"xianshi4\"}]},{\"title\":\"绩效\",\"icon\":\"jixiao\",\"code\":\"jixiao\",\"children\":[{\"title\":\"门店绩效\",\"path\":\"/storeJixiao\",\"code\":\"StoreJixiao\",\"icon\":\"jixiao1\"},{\"title\":\"督导绩效\",\"path\":\"/superReport\",\"code\":\"SuperReport\",\"icon\":\"jixiao1\"}]}" +
      ",{\"title\":\"报表\",\"icon\":\"report\",\"code\":\"report\",\"children\":[]}" +
      ",{\"title\":\"提成\",\"icon\":\"ticheng\",\"code\":\"commission\",\"children\":[{\"title\":\"规则管理\",\"path\":\"/ruleManagement\",\"code\":\"RuleManagement\",\"icon\":\"ticheng1\"},{\"title\":\"商品基础资料\",\"path\":\"/goodsBasicData\",\"code\":\"GoodsBasicData\",\"icon\":\"ticheng1\"}]}" +
      ",{\"title\":\"系统\",\"icon\":\"set\",\"code\":\"settings\",\"children\":[{\"title\":\"系统设置\",\"path\":\"/systemSetting\",\"code\":\"SystemSetting\",\"icon\":\"set1\"},{\"title\":\"用户设置\",\"path\":\"/userSetting\",\"code\":\"UserSetting\",\"icon\":\"set2\"},{\"title\":\"人店关系\",\"path\":\"/relationList\",\"code\":\"RelationList\",\"icon\":\"set3\"},{\"title\":\"人员登录状态管理\",\"path\":\"/userLog\",\"code\":\"UserLogList\",\"icon\":\"set4\"},{\"title\":\"语音通知记录\",\"path\":\"/voiceList\",\"code\":\"VoiceList\",\"icon\":\"set5\"},{\"title\":\"门店组织管理\",\"path\":\"/orgList\",\"code\":\"OrgList\",\"icon\":\"set6\"}]}]\n";
}
